spring:
  application:
    name: marketplace-app

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

management:
  endpoints:
    health:
      probes:
        enabled: true
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

  health:
    db:
      enabled: true
    diskspace:
      enabled: true

  info:
    env:
      enabled: true
